server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      # можно обойтись статическими маршрутами (проще для локалки)
      routes:
        - id: hotel-static
          uri: http://localhost:8081
          predicates:
            - Path=/api/**           # всё, что начинается с /api/** — в hotel-service
          filters:
            - RemoveRequestHeader=Cookie
        - id: booking-static
          uri: http://localhost:8082
          predicates:
            - Path=/booking/**,/bookings/**,/user/**
          filters:
            - RemoveRequestHeader=Cookie
    # если захочешь маршрутизацию через Eureka:
    # gateway:
    #   discovery:
    #     locator:
    #       enabled: true
    #       lower-case-service-id: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
