spring:
  application:
    name: BOOKING-SERVICE

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    metadata-map:
      management.port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,env,beans,loggers,metrics
  endpoint:
    health:
      show-details: always
